### PR TITLE
Add BNBToken and SampleBEP2Token

### PR DESCRIPTION
**Pull request by phoorichet**
Add both bin and ABI of BNBToken and SampleBEP2Token for the client to make a call to contracts on DappChain

### CODE REVIEW

**Comment by enlight** [comment]
I don't see any code referencing these contracts, is there a corresponding PR elsewhere?

**Comment by phoorichet** [comment]
Yes. we use it in this PR: https://github.com/loomnetwork/transfer-gateway-v2/pull/112

**Comment by enlight** [comment]
Is that the only place? If so can these contracts live in `transfer-gateway-v2` instead?

**Comment by phoorichet** [comment]
It is the only place. But the [erc20](https://github.com/loomnetwork/go-loom/blob/97b00e86fce0e0447bcf06abdcb3ac3338c69366/client/erc20/dappchain_erc20_contract.go#L46) client seems to always resolves the file in go-loom only. If we can have it load ABI from a custom path, then we shouldn't need this PR.

**Comment by phoorichet** [comment]
Just notice that all of the filed in struct is public. so yeah it should be fine. we can close this PR.

**Pull request closed without merging**
