### PR TITLE
Index to tx tags

### PR DESCRIPTION
**Pull request by Sriep**

### CODE REVIEW

**Comment by mattkanwisher** [comment]
@eduardonunesp

**Comment by eduardonunesp** [comment]
Yep testing

**Comment by eduardonunesp** [comment]
Works on PR https://github.com/loomnetwork/loom-js/pull/45

**Comment by mattkanwisher** [comment]
ok merging this in

**Comment by Sriep** [comment]
Expects https://github.com/loomnetwork/loomchain/pull/133

**Pull request merged**
